### ISSUE TITLE
Fix DeprecationWarnings in Python 3.7

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/akro#32]
See https://travis-ci.com/rlworkgroup/akro/jobs/199317054#L472 for an example log.

**Comment by sud0nick** [comment]
The warnings for the `theano` package will be removed with my PR since that package was removed.  As for the other packages there is a newer version of `tensorflow` that resolves this problem and an open issue for `protobuf`.

https://github.com/tensorflow/tensorflow/pull/26173
https://github.com/protocolbuffers/protobuf/labels/wait%20for%203.8.0%20release

**Comment by sud0nick** [comment]
Should be able to resolve this in October 2019.  https://github.com/protocolbuffers/protobuf/issues/5865#issuecomment-503442918

**Comment by sud0nick** [comment]
Looks like this may be fixed now.  I'll take a look at it.  https://github.com/protocolbuffers/protobuf/issues/5865#issuecomment-503442918

**Comment by ryanjulian** [comment]
Awesome, please do.

**Comment by ryanjulian** [comment]
@sud0nick can you verify that?

**Comment by sud0nick** [comment]
@ryanjulian yeah sorry, I didn't see this message before.  I'll take a look this week.

**Comment by sud0nick** [comment]
@ryanjulian protobuf 3.9 is out now and the issue was resolved in 3.8.  The same issue existed in theano and while I don't see any hard evidence that it was resolved if there's a newer release it should have been.  My only question is where are the package versions defined for the CI environment?  I don't see any specific version for protobuf called out anywhere in the akro repo.

https://github.com/protocolbuffers/protobuf/releases

**Comment by krzentner** [comment]
The package versions in the CI environment aren't documented anywhere, and it's entirely possible that the Travis build environment already has an older version of protobuf installed. Without explicit instructions to update it, pip won't.

Perhaps we should upgrade *all* of our dependencies in Travis to catch breakages?
